---
- name: Remove file from host
  hosts: linux
  gather_facts: false

  tasks:
    - name: Remove file
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ list }}"
