---
- name: Change Domain Admin Password
  hosts: bt-beg-int_dc1-beg
  gather_facts: False
  tasks:
    - name: Set Password
      set_fact:
        new_password: SingaporeNoOne! # "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
        new_password2: SingaporeNo.One! # "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
    - name: Change Password
      ansible.windows.win_user:
        name: "administrator"
        password: "{{ new_password }}"
    - name: Change Password
      ansible.windows.win_user:
        name: "administrator"
        password: "{{ new_password2 }}"