---
- name: Change Local Admin Password
  hosts: windows
  gather_facts: False
  vars: 
    - new_password: ""
  tasks:
    - name: Set Password
      set_fact:
        new_password: "{{ lookup('password', '/dev/null length=14 chars=ascii_letters,digits') }}"
    - name: Write Password
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: latest_local_passwords/{{ inventory_hostname }}.txt
        line: "{{ inventory_hostname }}:{{ new_password }}"
        create: yes
    - name: Change Password
      ansible.windows.win_user:
        name: "administrator"
        password: "{{ new_password }}"
    - name: Replace value in inventory
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: inventory.ini
        regexp: "^{{ inventory_hostname }} ansible_host={{ ansible_host }}.*$"
        line: "{{ inventory_hostname }} ansible_host={{ ansible_host }} os={{ os }} fqdn={{ fqdn }} ansible_password=\"{{ new_password }}\""
        state: present
    - name: Combine Password
      delegate_to: localhost
      ansible.builtin.assemble:
        src: latest_local_passwords
        dest: latest_local_passwords.txt
    - name: Delete content & directory
      delegate_to: localhost
      shell: rm -rf latest_local_passwords/*
      
# - hosts: linux
#   gather_facts: False
#   vars: 
#     - new_password: ""
#   tasks:
#     - name: Set Password
#       set_fact:
#         new_password: "{{ lookup('password', '/dev/null length=12') }}"
#     - name: Change Password
#       become: true
#       user:
#         name: "{{ ansible_user }}"
#         password: "{{ new_password | password_hash('sha512') }}"
#     - name: Write Password
#       delegate_to: localhost
#       ansible.builtin.lineinfile:
#         path: latest_local_passwords_linux/{{ inventory_hostname }}.txt
#         line: "{{ inventory_hostname }}:{{ new_password }}"
#         create: yes
#     - name: Replace value in inventory
#       delegate_to: localhost
#       ansible.builtin.lineinfile:
#         path: inventory.ini
#         regexp: "^{{ inventory_hostname }} ansible_host={{ ansible_host }}.*$"
#         line: "{{ inventory_hostname }} ansible_host={{ ansible_host }} ansible_password=\"{{ new_password }}\""
#         backrefs: yes
#         state: present
#     - name: Combine Password
#       delegate_to: localhost
#       ansible.builtin.assemble:
#         src: latest_local_passwords_linux
#         dest: latest_local_passwords_linux.txt
#     - name: Delete content & directory
#       delegate_to: localhost
#       shell: rm -rf latest_local_passwords_linux/*