---
- name: Force gpupdate
  hosts: windows
  gather_facts: False
  tasks:
    - name: gpupdate
      ansible.windows.win_command: "gpupdate /force"
    - name: Reboot
      ansible.windows.win_reboot:
