- name: group accessible by root only
  hosts: linux
  become: yes
  tasks:
  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /etc/group
      owner: root
      group: root
      mode: u-x,go-wx

  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /etc/group-
      owner: root
      group: root
      mode: u-x,go-wx