- name: Check shadow group empty
  hosts: linux
  become: yes
  tasks:
  - name: Check shadow group empty
    ansible.builtin.shell: awk -F {{":"}} '($1=="shadow") {print $NF}' /etc/group {{"#"}} awk -F{{":"}} -v GID="$(awk -F{{":"}} '($1=="shadow") {print $3}' /etc/group)" '($4==GID) {print $1}' /etc/passwd 
    register: out

  - name: Check shadow group empty
    debug: var=out.stdout_lines