---
- name: SSH key persistency install
  hosts: linux
  gather_facts: no
  tasks:
    - name: Copy SSH key
      ansible.posix.authorized_key:
        user: linux_user
        state: present
        key: "{{ lookup('file', 'keys/id_rsa.pub') }}"
