---
- name: Remove file from Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Removing file
      win_file:
        path: "{{ item }}"
        state: absent
      loop: "{{ list }}"
