---
- name: Remove file from host
  hosts: linux
  gather_facts: no
  become: True
  tasks:
    - name: Remove file
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ list }}"
