- name: enable NLA
  hosts: windows
  tasks:
  - name: enable NLA
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
      name: UserAuthentication
      data: 1
      type: dword

  - name: enable NLA
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
      name: SecurityLayer
      data: 2
      type: dword
