- name: Check port forwarding
  hosts: windows
  tasks:
  - name: Check
    ansible.windows.win_command: netsh interface portproxy show all
    register: out

  - name: Check
    debug: var=out.stdout_lines
    #empty = no port forwarding